import { Club } from './types';

// ============================================================
// Elite Striker - Clubs Database
// 40 clubs across 5 top European leagues
// ============================================================

export const LEAGUES = [
  { id: 'premier_league', name: 'Premier League', country: 'England', emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id: 'la_liga', name: 'La Liga', country: 'Spain', emoji: '🇪🇸' },
  { id: 'serie_a', name: 'Serie A', country: 'Italy', emoji: '🇮🇹' },
  { id: 'bundesliga', name: 'Bundesliga', country: 'Germany', emoji: '🇩🇪' },
  { id: 'ligue_1', name: 'Ligue 1', country: 'France', emoji: '🇫🇷' },
] as const;

export const CLUBS: Club[] = [
  // ============================================================
  // English Premier League (8 clubs)
  // ============================================================
  {
    id: 'arsenal',
    name: 'Arsenal',
    shortName: 'ARS',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 90,
    facilities: 92,
    finances: 88,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 88,
    youthDevelopment: 85,
    logo: '🔴',
    primaryColor: '#EF0107',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    shortName: 'CHE',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 88,
    facilities: 90,
    finances: 92,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 84,
    youthDevelopment: 78,
    logo: '🔵',
    primaryColor: '#034694',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    shortName: 'LIV',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 92,
    facilities: 91,
    finances: 90,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 89,
    youthDevelopment: 82,
    logo: '🔴',
    primaryColor: '#C8102E',
    secondaryColor: '#00B2A9',
  },
  {
    id: 'man_city',
    name: 'Manchester City',
    shortName: 'MCI',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 95,
    facilities: 96,
    finances: 97,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 93,
    youthDevelopment: 88,
    logo: '🩵',
    primaryColor: '#6CABDD',
    secondaryColor: '#1C2C5B',
  },
  {
    id: 'man_united',
    name: 'Manchester United',
    shortName: 'MUN',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 93,
    facilities: 93,
    finances: 95,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 82,
    youthDevelopment: 86,
    logo: '🔴',
    primaryColor: '#DA291C',
    secondaryColor: '#FBE122',
  },
  {
    id: 'tottenham',
    name: 'Tottenham Hotspur',
    shortName: 'TOT',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 85,
    facilities: 94,
    finances: 86,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 83,
    youthDevelopment: 80,
    logo: '⚪',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'newcastle',
    name: 'Newcastle United',
    shortName: 'NEW',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 82,
    facilities: 82,
    finances: 90,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 82,
    youthDevelopment: 75,
    logo: '⬛',
    primaryColor: '#241F20',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'aston_villa',
    name: 'Aston Villa',
    shortName: 'AVL',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 78,
    facilities: 80,
    finances: 82,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 80,
    youthDevelopment: 76,
    logo: '🟤',
    primaryColor: '#670E36',
    secondaryColor: '#95BFE5',
  },

  // ============================================================
  // Spanish La Liga (8 clubs)
  // ============================================================
  {
    id: 'real_madrid',
    name: 'Real Madrid',
    shortName: 'RMA',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 97,
    facilities: 95,
    finances: 98,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 94,
    youthDevelopment: 84,
    logo: '⚪',
    primaryColor: '#FEBE10',
    secondaryColor: '#00529F',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'BAR',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 96,
    facilities: 94,
    finances: 85,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 90,
    youthDevelopment: 92,
    logo: '🔵',
    primaryColor: '#A50044',
    secondaryColor: '#004D98',
  },
  {
    id: 'atletico_madrid',
    name: 'Atletico Madrid',
    shortName: 'ATM',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 87,
    facilities: 85,
    finances: 82,
    tacticalStyle: 'defensive',
    formation: '3-5-2',
    squadQuality: 85,
    youthDevelopment: 78,
    logo: '🔴',
    primaryColor: '#CB3524',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'sevilla',
    name: 'Sevilla FC',
    shortName: 'SEV',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 78,
    facilities: 78,
    finances: 72,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 77,
    youthDevelopment: 80,
    logo: '⚪',
    primaryColor: '#F43333',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'valencia',
    name: 'Valencia CF',
    shortName: 'VAL',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 74,
    facilities: 76,
    finances: 68,
    tacticalStyle: 'counter-attack',
    formation: '4-4-2',
    squadQuality: 73,
    youthDevelopment: 77,
    logo: '🦇',
    primaryColor: '#FFFFFF',
    secondaryColor: '#FF6B00',
  },
  {
    id: 'real_sociedad',
    name: 'Real Sociedad',
    shortName: 'RSO',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 73,
    facilities: 75,
    finances: 70,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 76,
    youthDevelopment: 83,
    logo: '🔵',
    primaryColor: '#003DA5',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'villarreal',
    name: 'Villarreal CF',
    shortName: 'VIL',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 72,
    facilities: 74,
    finances: 68,
    tacticalStyle: 'possession',
    formation: '4-4-2',
    squadQuality: 75,
    youthDevelopment: 76,
    logo: '🟡',
    primaryColor: '#FFE114',
    secondaryColor: '#005187',
  },
  {
    id: 'athletic_bilbao',
    name: 'Athletic Bilbao',
    shortName: 'ATH',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 74,
    facilities: 76,
    finances: 72,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 88,
    logo: '🔴',
    primaryColor: '#EE2523',
    secondaryColor: '#FFFFFF',
  },

  // ============================================================
  // Italian Serie A (8 clubs)
  // ============================================================
  {
    id: 'inter_milan',
    name: 'Inter Milan',
    shortName: 'INT',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 89,
    facilities: 88,
    finances: 86,
    tacticalStyle: 'counter-attack',
    formation: '3-5-2',
    squadQuality: 87,
    youthDevelopment: 78,
    logo: '🔵',
    primaryColor: '#0068A8',
    secondaryColor: '#000000',
  },
  {
    id: 'ac_milan',
    name: 'AC Milan',
    shortName: 'ACM',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 88,
    facilities: 86,
    finances: 84,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 84,
    youthDevelopment: 75,
    logo: '🔴',
    primaryColor: '#FB090B',
    secondaryColor: '#000000',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'JUV',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 90,
    facilities: 90,
    finances: 85,
    tacticalStyle: 'defensive',
    formation: '3-5-2',
    squadQuality: 85,
    youthDevelopment: 80,
    logo: '⬛',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'napoli',
    name: 'SSC Napoli',
    shortName: 'NAP',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 83,
    facilities: 82,
    finances: 78,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 84,
    youthDevelopment: 74,
    logo: '🔵',
    primaryColor: '#12A0D7',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'roma',
    name: 'AS Roma',
    shortName: 'ROM',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 80,
    facilities: 80,
    finances: 76,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 79,
    youthDevelopment: 76,
    logo: '🟡',
    primaryColor: '#8E1F2F',
    secondaryColor: '#F0BC42',
  },
  {
    id: 'lazio',
    name: 'SS Lazio',
    shortName: 'LAZ',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 77,
    facilities: 78,
    finances: 74,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 78,
    youthDevelopment: 72,
    logo: '🔵',
    primaryColor: '#87D8F7',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'atalanta',
    name: 'Atalanta',
    shortName: 'ATA',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 78,
    facilities: 76,
    finances: 74,
    tacticalStyle: 'attacking',
    formation: '3-4-2-1',
    squadQuality: 81,
    youthDevelopment: 82,
    logo: '🔵',
    primaryColor: '#1E71B8',
    secondaryColor: '#000000',
  },
  {
    id: 'fiorentina',
    name: 'ACF Fiorentina',
    shortName: 'FIO',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 73,
    facilities: 74,
    finances: 70,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 74,
    logo: '🟣',
    primaryColor: '#482E92',
    secondaryColor: '#FFFFFF',
  },

  // ============================================================
  // German Bundesliga (8 clubs)
  // ============================================================
  {
    id: 'bayern_munich',
    name: 'FC Bayern Munich',
    shortName: 'BAY',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 95,
    facilities: 96,
    finances: 95,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 91,
    youthDevelopment: 86,
    logo: '🔴',
    primaryColor: '#DC052D',
    secondaryColor: '#0066B2',
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 87,
    facilities: 88,
    finances: 82,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 85,
    youthDevelopment: 90,
    logo: '🟡',
    primaryColor: '#FDE100',
    secondaryColor: '#000000',
  },
  {
    id: 'rb_leipzig',
    name: 'RB Leipzig',
    shortName: 'RBL',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 79,
    facilities: 86,
    finances: 84,
    tacticalStyle: 'counter-attack',
    formation: '4-4-2',
    squadQuality: 82,
    youthDevelopment: 80,
    logo: '🔴',
    primaryColor: '#DD0741',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'leverkusen',
    name: 'Bayer Leverkusen',
    shortName: 'B04',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 80,
    facilities: 84,
    finances: 80,
    tacticalStyle: 'attacking',
    formation: '3-4-2-1',
    squadQuality: 86,
    youthDevelopment: 82,
    logo: '🔴',
    primaryColor: '#E32221',
    secondaryColor: '#000000',
  },
  {
    id: 'wolfsburg',
    name: 'VfL Wolfsburg',
    shortName: 'WOB',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 70,
    facilities: 78,
    finances: 76,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 72,
    youthDevelopment: 70,
    logo: '🟢',
    primaryColor: '#65B32E',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'frankfurt',
    name: 'Eintracht Frankfurt',
    shortName: 'SGE',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 75,
    facilities: 76,
    finances: 74,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 77,
    youthDevelopment: 73,
    logo: '🦅',
    primaryColor: '#E1000F',
    secondaryColor: '#000000',
  },
  {
    id: 'freiburg',
    name: 'SC Freiburg',
    shortName: 'SCF',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 70,
    facilities: 72,
    finances: 66,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 74,
    youthDevelopment: 85,
    logo: '⚫',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'union_berlin',
    name: 'Union Berlin',
    shortName: 'FCU',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 68,
    facilities: 68,
    finances: 62,
    tacticalStyle: 'defensive',
    formation: '3-5-2',
    squadQuality: 71,
    youthDevelopment: 68,
    logo: '🔴',
    primaryColor: '#EB1923',
    secondaryColor: '#FFFFFF',
  },

  // ============================================================
  // French Ligue 1 (8 clubs)
  // ============================================================
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 93,
    facilities: 94,
    finances: 96,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 90,
    youthDevelopment: 78,
    logo: '🔵',
    primaryColor: '#004170',
    secondaryColor: '#DA291C',
  },
  {
    id: 'marseille',
    name: 'Olympique de Marseille',
    shortName: 'OM',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 80,
    facilities: 78,
    finances: 74,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 78,
    youthDevelopment: 74,
    logo: '⚪',
    primaryColor: '#2FAEE0',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'lyon',
    name: 'Olympique Lyonnais',
    shortName: 'OL',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 77,
    facilities: 80,
    finances: 68,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 76,
    youthDevelopment: 82,
    logo: '🔵',
    primaryColor: '#1B3C8D',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'monaco',
    name: 'AS Monaco',
    shortName: 'ASM',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 76,
    facilities: 78,
    finances: 76,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 77,
    youthDevelopment: 80,
    logo: '🔴',
    primaryColor: '#E7192C',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'lille',
    name: 'LOSC Lille',
    shortName: 'LIL',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 74,
    facilities: 76,
    finances: 70,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 78,
    logo: '🔴',
    primaryColor: '#E2001A',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'nice',
    name: 'OGC Nice',
    shortName: 'NIC',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 72,
    facilities: 74,
    finances: 72,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 74,
    youthDevelopment: 72,
    logo: '🔴',
    primaryColor: '#CC0000',
    secondaryColor: '#000000',
  },
  {
    id: 'rennes',
    name: 'Stade Rennais',
    shortName: 'REN',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 71,
    facilities: 74,
    finances: 68,
    tacticalStyle: 'attacking',
    formation: '4-4-2',
    squadQuality: 74,
    youthDevelopment: 80,
    logo: '🔴',
    primaryColor: '#E2001A',
    secondaryColor: '#000000',
  },
  {
    id: 'lens',
    name: 'RC Lens',
    shortName: 'RCL',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 72,
    facilities: 72,
    finances: 66,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 75,
    youthDevelopment: 73,
    logo: '🔴',
    primaryColor: '#FFE100',
    secondaryColor: '#E2001A',
  },
];

// Enrich raw club data with computed fields matching Club interface
function enrichClub(raw: Omit<Club, 'quality' | 'budget' | 'wageBudget' | 'squadSize' | 'style' | 'needsPositions'> & { squadQuality: number; finances: number; tacticalStyle: string }): Club {
  const styleMap: Record<string, { attacking: number; possession: number; pressing: number; defensive: number }> = {
    'attacking':     { attacking: 80, possession: 55, pressing: 65, defensive: 30 },
    'defensive':     { attacking: 30, possession: 45, pressing: 55, defensive: 80 },
    'counter-attack':{ attacking: 55, possession: 40, pressing: 60, defensive: 65 },
    'possession':    { attacking: 65, possession: 85, pressing: 50, defensive: 40 },
  };
  const allPositions: Position[] = ['GK','CB','LB','RB','CDM','CM','CAM','LW','RW','ST'];
  return {
    ...raw,
    quality: raw.squadQuality,
    budget: Math.round(raw.finances * raw.reputation * 5000),
    wageBudget: Math.round(raw.finances * raw.reputation * 100),
    squadSize: 22 + Math.floor(Math.random() * 6),
    style: styleMap[raw.tacticalStyle] ?? styleMap['possession'],
    needsPositions: allPositions.filter(() => Math.random() < 0.3).slice(0, 3),
  };
}

// Enriched clubs list matching the full Club type
export const ENRICHED_CLUBS: Club[] = (CLUBS as any[]).map(enrichClub);

// Helper: Get clubs by league
export function getClubsByLeague(leagueId: string): Club[] {
  return ENRICHED_CLUBS.filter(club => club.league === leagueId);
}

// Helper: Get club by ID
export function getClubById(id: string): Club | undefined {
  return ENRICHED_CLUBS.find(club => club.id === id);
}

// Helper: Get clubs by tier
export function getClubsByTier(tier: number): Club[] {
  return ENRICHED_CLUBS.filter(club => club.tier === tier);
}

// Helper: Get league info by ID
export function getLeagueById(leagueId: string) {
  return LEAGUES.find(league => league.id === leagueId);
}
