import { Club } from './types';

// ============================================================
// Elite Striker - Clubs Database
// 96 clubs across 5 top European leagues
// ============================================================

export const LEAGUES = [
  { id: 'premier_league', name: 'Premier League', country: 'England', emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', teamCount: 20 },
  { id: 'la_liga', name: 'La Liga', country: 'Spain', emoji: '🇪🇸', teamCount: 20 },
  { id: 'serie_a', name: 'Serie A', country: 'Italy', emoji: '🇮🇹', teamCount: 20 },
  { id: 'bundesliga', name: 'Bundesliga', country: 'Germany', emoji: '🇩🇪', teamCount: 18 },
  { id: 'ligue_1', name: 'Ligue 1', country: 'France', emoji: '🇫🇷', teamCount: 18 },
] as const;

// Cup competition names per league
export const CUP_NAMES: Record<string, { name: string; emoji: string }> = {
  premier_league: { name: 'FA Cup', emoji: '🏆' },
  la_liga: { name: 'Copa del Rey', emoji: '👑' },
  serie_a: { name: 'Coppa Italia', emoji: '🇮🇹' },
  bundesliga: { name: 'DFB-Pokal', emoji: '🇩🇪' },
  ligue_1: { name: 'Coupe de France', emoji: '🇫🇷' },
};

// Cup match weeks (every 4 weeks)
export const CUP_MATCH_WEEKS = [4, 8, 12, 16, 20, 24, 28, 32, 36];

export const CLUBS: Club[] = [
  // ============================================================
  // English Premier League (20 clubs)
  // ============================================================
  {
    id: 'arsenal',
    name: 'Arsenal',
    shortName: 'ARS',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 90,
    facilities: 92,
    finances: 88,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 88,
    youthDevelopment: 85,
    logo: '🔴',
    primaryColor: '#EF0107',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    shortName: 'CHE',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 88,
    facilities: 90,
    finances: 92,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 84,
    youthDevelopment: 78,
    logo: '🔵',
    primaryColor: '#034694',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    shortName: 'LIV',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 92,
    facilities: 91,
    finances: 90,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 89,
    youthDevelopment: 82,
    logo: '🔴',
    primaryColor: '#C8102E',
    secondaryColor: '#00B2A9',
  },
  {
    id: 'man_city',
    name: 'Manchester City',
    shortName: 'MCI',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 95,
    facilities: 96,
    finances: 97,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 93,
    youthDevelopment: 88,
    logo: '🩵',
    primaryColor: '#6CABDD',
    secondaryColor: '#1C2C5B',
  },
  {
    id: 'man_united',
    name: 'Manchester United',
    shortName: 'MUN',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 93,
    facilities: 93,
    finances: 95,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 82,
    youthDevelopment: 86,
    logo: '🔴',
    primaryColor: '#DA291C',
    secondaryColor: '#FBE122',
  },
  {
    id: 'tottenham',
    name: 'Tottenham Hotspur',
    shortName: 'TOT',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 85,
    facilities: 94,
    finances: 86,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 83,
    youthDevelopment: 80,
    logo: '⚪',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'newcastle',
    name: 'Newcastle United',
    shortName: 'NEW',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 82,
    facilities: 82,
    finances: 90,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 82,
    youthDevelopment: 75,
    logo: '⬛',
    primaryColor: '#241F20',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'aston_villa',
    name: 'Aston Villa',
    shortName: 'AVL',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 78,
    facilities: 80,
    finances: 82,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 80,
    youthDevelopment: 76,
    logo: '🟤',
    primaryColor: '#670E36',
    secondaryColor: '#95BFE5',
  },
  {
    id: 'brighton',
    name: 'Brighton & Hove Albion',
    shortName: 'BHA',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 74,
    facilities: 82,
    finances: 76,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 82,
    logo: '🔵',
    primaryColor: '#0057B8',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'west_ham',
    name: 'West Ham United',
    shortName: 'WHU',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 73,
    facilities: 78,
    finances: 74,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 74,
    youthDevelopment: 72,
    logo: '🟤',
    primaryColor: '#7A263A',
    secondaryColor: '#1BB1E7',
  },
  {
    id: 'crystal_palace',
    name: 'Crystal Palace',
    shortName: 'CRY',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 68,
    facilities: 70,
    finances: 68,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 70,
    youthDevelopment: 66,
    logo: '🔴',
    primaryColor: '#1B458F',
    secondaryColor: '#C4122E',
  },
  {
    id: 'bournemouth',
    name: 'AFC Bournemouth',
    shortName: 'BOU',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 65,
    facilities: 66,
    finances: 66,
    tacticalStyle: 'attacking',
    formation: '4-4-2',
    squadQuality: 68,
    youthDevelopment: 62,
    logo: '🔴',
    primaryColor: '#DA291C',
    secondaryColor: '#000000',
  },
  {
    id: 'fulham',
    name: 'Fulham FC',
    shortName: 'FUL',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 67,
    facilities: 72,
    finances: 72,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 70,
    youthDevelopment: 68,
    logo: '⚪',
    primaryColor: '#000000',
    secondaryColor: '#CC0000',
  },
  {
    id: 'wolves',
    name: 'Wolverhampton Wanderers',
    shortName: 'WOL',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 68,
    facilities: 70,
    finances: 68,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 69,
    youthDevelopment: 70,
    logo: '🟠',
    primaryColor: '#FDB913',
    secondaryColor: '#231F20',
  },
  {
    id: 'everton',
    name: 'Everton FC',
    shortName: 'EVE',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 72,
    facilities: 74,
    finances: 64,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 68,
    youthDevelopment: 74,
    logo: '🔵',
    primaryColor: '#003399',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'brentford',
    name: 'Brentford FC',
    shortName: 'BRE',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 66,
    facilities: 72,
    finances: 70,
    tacticalStyle: 'possession',
    formation: '3-5-2',
    squadQuality: 70,
    youthDevelopment: 72,
    logo: '🔴',
    primaryColor: '#E30613',
    secondaryColor: '#FBB800',
  },
  {
    id: 'nottingham_forest',
    name: 'Nottingham Forest',
    shortName: 'NFO',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 65,
    facilities: 68,
    finances: 72,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 68,
    youthDevelopment: 66,
    logo: '🔴',
    primaryColor: '#DD0000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'burnley',
    name: 'Burnley FC',
    shortName: 'BUR',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 60,
    facilities: 64,
    finances: 60,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 62,
    youthDevelopment: 62,
    logo: '🟤',
    primaryColor: '#6C1D45',
    secondaryColor: '#7AB6E8',
  },
  {
    id: 'sheffield_united',
    name: 'Sheffield United',
    shortName: 'SHU',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 58,
    facilities: 62,
    finances: 58,
    tacticalStyle: 'counter-attack',
    formation: '3-5-2',
    squadQuality: 60,
    youthDevelopment: 64,
    logo: '🔴',
    primaryColor: '#EE2737',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'luton_town',
    name: 'Luton Town',
    shortName: 'LUT',
    league: 'premier_league',
    country: 'England',
    tier: 1,
    reputation: 55,
    facilities: 56,
    finances: 54,
    tacticalStyle: 'counter-attack',
    formation: '4-4-2',
    squadQuality: 58,
    youthDevelopment: 60,
    logo: '🟠',
    primaryColor: '#F78F1E',
    secondaryColor: '#1E3A5F',
  },

  // ============================================================
  // Spanish La Liga (20 clubs)
  // ============================================================
  {
    id: 'real_madrid',
    name: 'Real Madrid',
    shortName: 'RMA',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 97,
    facilities: 95,
    finances: 98,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 94,
    youthDevelopment: 84,
    logo: '⚪',
    primaryColor: '#FEBE10',
    secondaryColor: '#00529F',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'BAR',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 96,
    facilities: 94,
    finances: 85,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 90,
    youthDevelopment: 92,
    logo: '🔵',
    primaryColor: '#A50044',
    secondaryColor: '#004D98',
  },
  {
    id: 'atletico_madrid',
    name: 'Atletico Madrid',
    shortName: 'ATM',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 87,
    facilities: 85,
    finances: 82,
    tacticalStyle: 'defensive',
    formation: '3-5-2',
    squadQuality: 85,
    youthDevelopment: 78,
    logo: '🔴',
    primaryColor: '#CB3524',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'sevilla',
    name: 'Sevilla FC',
    shortName: 'SEV',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 78,
    facilities: 78,
    finances: 72,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 77,
    youthDevelopment: 80,
    logo: '⚪',
    primaryColor: '#F43333',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'valencia',
    name: 'Valencia CF',
    shortName: 'VAL',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 74,
    facilities: 76,
    finances: 68,
    tacticalStyle: 'counter-attack',
    formation: '4-4-2',
    squadQuality: 73,
    youthDevelopment: 77,
    logo: '🦇',
    primaryColor: '#FFFFFF',
    secondaryColor: '#FF6B00',
  },
  {
    id: 'real_sociedad',
    name: 'Real Sociedad',
    shortName: 'RSO',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 73,
    facilities: 75,
    finances: 70,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 76,
    youthDevelopment: 83,
    logo: '🔵',
    primaryColor: '#003DA5',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'villarreal',
    name: 'Villarreal CF',
    shortName: 'VIL',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 72,
    facilities: 74,
    finances: 68,
    tacticalStyle: 'possession',
    formation: '4-4-2',
    squadQuality: 75,
    youthDevelopment: 76,
    logo: '🟡',
    primaryColor: '#FFE114',
    secondaryColor: '#005187',
  },
  {
    id: 'athletic_bilbao',
    name: 'Athletic Bilbao',
    shortName: 'ATH',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 74,
    facilities: 76,
    finances: 72,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 88,
    logo: '🔴',
    primaryColor: '#EE2523',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'real_betis',
    name: 'Real Betis',
    shortName: 'BET',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 73,
    facilities: 74,
    finances: 68,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 75,
    youthDevelopment: 73,
    logo: '🟢',
    primaryColor: '#00954C',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'girona',
    name: 'Girona FC',
    shortName: 'GIR',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 70,
    facilities: 68,
    finances: 66,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 76,
    youthDevelopment: 68,
    logo: '🔴',
    primaryColor: '#CD2534',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'celta_vigo',
    name: 'Celta Vigo',
    shortName: 'CEL',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 67,
    facilities: 68,
    finances: 62,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 70,
    youthDevelopment: 72,
    logo: '🔵',
    primaryColor: '#8AC3EE',
    secondaryColor: '#E53027',
  },
  {
    id: 'osasuna',
    name: 'CA Osasuna',
    shortName: 'OSA',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 64,
    facilities: 66,
    finances: 60,
    tacticalStyle: 'counter-attack',
    formation: '4-4-2',
    squadQuality: 68,
    youthDevelopment: 66,
    logo: '🔴',
    primaryColor: '#0A346F',
    secondaryColor: '#C6000A',
  },
  {
    id: 'mallorca',
    name: 'RCD Mallorca',
    shortName: 'MLL',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 62,
    facilities: 64,
    finances: 58,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 66,
    youthDevelopment: 64,
    logo: '🔴',
    primaryColor: '#E20613',
    secondaryColor: '#000000',
  },
  {
    id: 'getafe',
    name: 'Getafe CF',
    shortName: 'GET',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 62,
    facilities: 64,
    finances: 58,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 65,
    youthDevelopment: 62,
    logo: '🔵',
    primaryColor: '#004999',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'rayo_vallecano',
    name: 'Rayo Vallecano',
    shortName: 'RAY',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 60,
    facilities: 60,
    finances: 54,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 64,
    youthDevelopment: 62,
    logo: '🔴',
    primaryColor: '#E53027',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'alaves',
    name: 'Deportivo Alaves',
    shortName: 'ALA',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 58,
    facilities: 60,
    finances: 54,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 62,
    youthDevelopment: 60,
    logo: '🔵',
    primaryColor: '#003DA5',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'cadiz',
    name: 'Cadiz CF',
    shortName: 'CAD',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 57,
    facilities: 58,
    finances: 52,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 61,
    youthDevelopment: 58,
    logo: '🟡',
    primaryColor: '#FDD835',
    secondaryColor: '#003DA5',
  },
  {
    id: 'las_palmas',
    name: 'UD Las Palmas',
    shortName: 'LPA',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 58,
    facilities: 62,
    finances: 52,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 64,
    youthDevelopment: 70,
    logo: '🟡',
    primaryColor: '#FDD835',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'almeria',
    name: 'UD Almeria',
    shortName: 'ALM',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 55,
    facilities: 58,
    finances: 56,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 60,
    youthDevelopment: 62,
    logo: '🔴',
    primaryColor: '#EE1111',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'granada',
    name: 'Granada CF',
    shortName: 'GRA',
    league: 'la_liga',
    country: 'Spain',
    tier: 1,
    reputation: 55,
    facilities: 56,
    finances: 50,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 58,
    youthDevelopment: 58,
    logo: '🔴',
    primaryColor: '#E30613',
    secondaryColor: '#FFFFFF',
  },

  // ============================================================
  // Italian Serie A (20 clubs)
  // ============================================================
  {
    id: 'inter_milan',
    name: 'Inter Milan',
    shortName: 'INT',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 89,
    facilities: 88,
    finances: 86,
    tacticalStyle: 'counter-attack',
    formation: '3-5-2',
    squadQuality: 87,
    youthDevelopment: 78,
    logo: '🔵',
    primaryColor: '#0068A8',
    secondaryColor: '#000000',
  },
  {
    id: 'ac_milan',
    name: 'AC Milan',
    shortName: 'ACM',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 88,
    facilities: 86,
    finances: 84,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 84,
    youthDevelopment: 75,
    logo: '🔴',
    primaryColor: '#FB090B',
    secondaryColor: '#000000',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'JUV',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 90,
    facilities: 90,
    finances: 85,
    tacticalStyle: 'defensive',
    formation: '3-5-2',
    squadQuality: 85,
    youthDevelopment: 80,
    logo: '⬛',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'napoli',
    name: 'SSC Napoli',
    shortName: 'NAP',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 83,
    facilities: 82,
    finances: 78,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 84,
    youthDevelopment: 74,
    logo: '🔵',
    primaryColor: '#12A0D7',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'roma',
    name: 'AS Roma',
    shortName: 'ROM',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 80,
    facilities: 80,
    finances: 76,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 79,
    youthDevelopment: 76,
    logo: '🟡',
    primaryColor: '#8E1F2F',
    secondaryColor: '#F0BC42',
  },
  {
    id: 'lazio',
    name: 'SS Lazio',
    shortName: 'LAZ',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 77,
    facilities: 78,
    finances: 74,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 78,
    youthDevelopment: 72,
    logo: '🔵',
    primaryColor: '#87D8F7',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'atalanta',
    name: 'Atalanta',
    shortName: 'ATA',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 78,
    facilities: 76,
    finances: 74,
    tacticalStyle: 'attacking',
    formation: '3-4-2-1',
    squadQuality: 81,
    youthDevelopment: 82,
    logo: '🔵',
    primaryColor: '#1E71B8',
    secondaryColor: '#000000',
  },
  {
    id: 'fiorentina',
    name: 'ACF Fiorentina',
    shortName: 'FIO',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 73,
    facilities: 74,
    finances: 70,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 74,
    logo: '🟣',
    primaryColor: '#482E92',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'bologna',
    name: 'Bologna FC',
    shortName: 'BOL',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 70,
    facilities: 72,
    finances: 66,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 74,
    youthDevelopment: 72,
    logo: '🔴',
    primaryColor: '#1A2C48',
    secondaryColor: '#A11E22',
  },
  {
    id: 'monza',
    name: 'AC Monza',
    shortName: 'MON',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 62,
    facilities: 66,
    finances: 68,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 66,
    youthDevelopment: 62,
    logo: '🔴',
    primaryColor: '#CE0E2D',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'torino',
    name: 'Torino FC',
    shortName: 'TOR',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 68,
    facilities: 70,
    finances: 64,
    tacticalStyle: 'counter-attack',
    formation: '3-5-2',
    squadQuality: 72,
    youthDevelopment: 70,
    logo: '🟤',
    primaryColor: '#8B0000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'udinese',
    name: 'Udinese Calcio',
    shortName: 'UDI',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 64,
    facilities: 66,
    finances: 60,
    tacticalStyle: 'counter-attack',
    formation: '3-5-2',
    squadQuality: 68,
    youthDevelopment: 74,
    logo: '⚪',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'sassuolo',
    name: 'Sassuolo Calcio',
    shortName: 'SAS',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 63,
    facilities: 66,
    finances: 60,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 68,
    youthDevelopment: 72,
    logo: '🟢',
    primaryColor: '#00A850',
    secondaryColor: '#000000',
  },
  {
    id: 'empoli',
    name: 'Empoli FC',
    shortName: 'EMP',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 60,
    facilities: 62,
    finances: 54,
    tacticalStyle: 'possession',
    formation: '4-3-1-2',
    squadQuality: 64,
    youthDevelopment: 72,
    logo: '🔵',
    primaryColor: '#005BA9',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'lecce',
    name: 'US Lecce',
    shortName: 'LEC',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 58,
    facilities: 60,
    finances: 52,
    tacticalStyle: 'defensive',
    formation: '4-3-3',
    squadQuality: 62,
    youthDevelopment: 64,
    logo: '🟡',
    primaryColor: '#FDD835',
    secondaryColor: '#E30613',
  },
  {
    id: 'cagliari',
    name: 'Cagliari Calcio',
    shortName: 'CAG',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 60,
    facilities: 62,
    finances: 56,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 64,
    youthDevelopment: 66,
    logo: '🔴',
    primaryColor: '#92001A',
    secondaryColor: '#003DA5',
  },
  {
    id: 'genoa',
    name: 'Genoa CFC',
    shortName: 'GEN',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 63,
    facilities: 64,
    finances: 58,
    tacticalStyle: 'defensive',
    formation: '3-5-2',
    squadQuality: 66,
    youthDevelopment: 66,
    logo: '🔴',
    primaryColor: '#9E1B32',
    secondaryColor: '#003DA5',
  },
  {
    id: 'verona',
    name: 'Hellas Verona',
    shortName: 'VER',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 58,
    facilities: 60,
    finances: 52,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 62,
    youthDevelopment: 62,
    logo: '🟡',
    primaryColor: '#003DA5',
    secondaryColor: '#FDD835',
  },
  {
    id: 'frosinone',
    name: 'Frosinone Calcio',
    shortName: 'FRO',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 55,
    facilities: 56,
    finances: 50,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 60,
    youthDevelopment: 60,
    logo: '🟡',
    primaryColor: '#FDD835',
    secondaryColor: '#0066CC',
  },
  {
    id: 'salernitana',
    name: 'US Salernitana',
    shortName: 'SAL',
    league: 'serie_a',
    country: 'Italy',
    tier: 1,
    reputation: 55,
    facilities: 56,
    finances: 50,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 58,
    youthDevelopment: 58,
    logo: '🟤',
    primaryColor: '#6A0032',
    secondaryColor: '#FFFFFF',
  },

  // ============================================================
  // German Bundesliga (18 clubs)
  // ============================================================
  {
    id: 'bayern_munich',
    name: 'FC Bayern Munich',
    shortName: 'BAY',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 95,
    facilities: 96,
    finances: 95,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 91,
    youthDevelopment: 86,
    logo: '🔴',
    primaryColor: '#DC052D',
    secondaryColor: '#0066B2',
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 87,
    facilities: 88,
    finances: 82,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 85,
    youthDevelopment: 90,
    logo: '🟡',
    primaryColor: '#FDE100',
    secondaryColor: '#000000',
  },
  {
    id: 'rb_leipzig',
    name: 'RB Leipzig',
    shortName: 'RBL',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 79,
    facilities: 86,
    finances: 84,
    tacticalStyle: 'counter-attack',
    formation: '4-4-2',
    squadQuality: 82,
    youthDevelopment: 80,
    logo: '🔴',
    primaryColor: '#DD0741',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'leverkusen',
    name: 'Bayer Leverkusen',
    shortName: 'B04',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 80,
    facilities: 84,
    finances: 80,
    tacticalStyle: 'attacking',
    formation: '3-4-2-1',
    squadQuality: 86,
    youthDevelopment: 82,
    logo: '🔴',
    primaryColor: '#E32221',
    secondaryColor: '#000000',
  },
  {
    id: 'wolfsburg',
    name: 'VfL Wolfsburg',
    shortName: 'WOB',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 70,
    facilities: 78,
    finances: 76,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 72,
    youthDevelopment: 70,
    logo: '🟢',
    primaryColor: '#65B32E',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'frankfurt',
    name: 'Eintracht Frankfurt',
    shortName: 'SGE',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 75,
    facilities: 76,
    finances: 74,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 77,
    youthDevelopment: 73,
    logo: '🦅',
    primaryColor: '#E1000F',
    secondaryColor: '#000000',
  },
  {
    id: 'freiburg',
    name: 'SC Freiburg',
    shortName: 'SCF',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 70,
    facilities: 72,
    finances: 66,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 74,
    youthDevelopment: 85,
    logo: '⚫',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'union_berlin',
    name: 'Union Berlin',
    shortName: 'FCU',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 68,
    facilities: 68,
    finances: 62,
    tacticalStyle: 'defensive',
    formation: '3-5-2',
    squadQuality: 71,
    youthDevelopment: 68,
    logo: '🔴',
    primaryColor: '#EB1923',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'stuttgart',
    name: 'VfB Stuttgart',
    shortName: 'VFB',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 73,
    facilities: 76,
    finances: 70,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 78,
    logo: '⚪',
    primaryColor: '#E32219',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'hoffenheim',
    name: 'TSG Hoffenheim',
    shortName: 'TSG',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 66,
    facilities: 74,
    finances: 70,
    tacticalStyle: 'possession',
    formation: '3-5-2',
    squadQuality: 70,
    youthDevelopment: 72,
    logo: '🔵',
    primaryColor: '#0053A0',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'mainz',
    name: '1. FSV Mainz 05',
    shortName: 'M05',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 63,
    facilities: 66,
    finances: 60,
    tacticalStyle: 'counter-attack',
    formation: '3-5-2',
    squadQuality: 66,
    youthDevelopment: 68,
    logo: '🔴',
    primaryColor: '#C3141E',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'augsburg',
    name: 'FC Augsburg',
    shortName: 'FCA',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 60,
    facilities: 64,
    finances: 58,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 64,
    youthDevelopment: 62,
    logo: '🔴',
    primaryColor: '#BA3733',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'werder_bremen',
    name: 'SV Werder Bremen',
    shortName: 'SVW',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 68,
    facilities: 70,
    finances: 64,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 70,
    youthDevelopment: 74,
    logo: '🟢',
    primaryColor: '#1D9053',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'bochum',
    name: 'VfL Bochum',
    shortName: 'BOC',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 58,
    facilities: 60,
    finances: 54,
    tacticalStyle: 'counter-attack',
    formation: '4-4-2',
    squadQuality: 62,
    youthDevelopment: 60,
    logo: '🔵',
    primaryColor: '#005BA9',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'koln',
    name: '1. FC Koln',
    shortName: 'KOE',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 64,
    facilities: 66,
    finances: 60,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 66,
    youthDevelopment: 68,
    logo: '⚪',
    primaryColor: '#ED1C24',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'heidenheim',
    name: '1. FC Heidenheim',
    shortName: 'FCH',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 56,
    facilities: 58,
    finances: 52,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 60,
    youthDevelopment: 58,
    logo: '🔴',
    primaryColor: '#E30613',
    secondaryColor: '#003DA5',
  },
  {
    id: 'darmstadt',
    name: 'SV Darmstadt 98',
    shortName: 'D98',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 55,
    facilities: 56,
    finances: 50,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 58,
    youthDevelopment: 56,
    logo: '🔵',
    primaryColor: '#004E9E',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'gladbach',
    name: 'Borussia Monchengladbach',
    shortName: 'BMG',
    league: 'bundesliga',
    country: 'Germany',
    tier: 1,
    reputation: 68,
    facilities: 72,
    finances: 66,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 70,
    youthDevelopment: 72,
    logo: '⚪',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },

  // ============================================================
  // French Ligue 1 (18 clubs)
  // ============================================================
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 93,
    facilities: 94,
    finances: 96,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 90,
    youthDevelopment: 78,
    logo: '🔵',
    primaryColor: '#004170',
    secondaryColor: '#DA291C',
  },
  {
    id: 'marseille',
    name: 'Olympique de Marseille',
    shortName: 'OM',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 80,
    facilities: 78,
    finances: 74,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 78,
    youthDevelopment: 74,
    logo: '⚪',
    primaryColor: '#2FAEE0',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'lyon',
    name: 'Olympique Lyonnais',
    shortName: 'OL',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 77,
    facilities: 80,
    finances: 68,
    tacticalStyle: 'attacking',
    formation: '4-3-3',
    squadQuality: 76,
    youthDevelopment: 82,
    logo: '🔵',
    primaryColor: '#1B3C8D',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'monaco',
    name: 'AS Monaco',
    shortName: 'ASM',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 76,
    facilities: 78,
    finances: 76,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 77,
    youthDevelopment: 80,
    logo: '🔴',
    primaryColor: '#E7192C',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'lille',
    name: 'LOSC Lille',
    shortName: 'LIL',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 74,
    facilities: 76,
    finances: 70,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 76,
    youthDevelopment: 78,
    logo: '🔴',
    primaryColor: '#E2001A',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'nice',
    name: 'OGC Nice',
    shortName: 'NIC',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 72,
    facilities: 74,
    finances: 72,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 74,
    youthDevelopment: 72,
    logo: '🔴',
    primaryColor: '#CC0000',
    secondaryColor: '#000000',
  },
  {
    id: 'rennes',
    name: 'Stade Rennais',
    shortName: 'REN',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 71,
    facilities: 74,
    finances: 68,
    tacticalStyle: 'attacking',
    formation: '4-4-2',
    squadQuality: 74,
    youthDevelopment: 80,
    logo: '🔴',
    primaryColor: '#E2001A',
    secondaryColor: '#000000',
  },
  {
    id: 'lens',
    name: 'RC Lens',
    shortName: 'RCL',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 72,
    facilities: 72,
    finances: 66,
    tacticalStyle: 'counter-attack',
    formation: '3-4-2-1',
    squadQuality: 75,
    youthDevelopment: 73,
    logo: '🔴',
    primaryColor: '#FFE100',
    secondaryColor: '#E2001A',
  },
  {
    id: 'strasbourg',
    name: 'RC Strasbourg',
    shortName: 'RCS',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 64,
    facilities: 66,
    finances: 62,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 66,
    youthDevelopment: 68,
    logo: '🔵',
    primaryColor: '#005BA9',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'toulouse',
    name: 'Toulouse FC',
    shortName: 'TFC',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 64,
    facilities: 68,
    finances: 62,
    tacticalStyle: 'possession',
    formation: '4-3-3',
    squadQuality: 68,
    youthDevelopment: 70,
    logo: '🟣',
    primaryColor: '#7B2D8B',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'montpellier',
    name: 'Montpellier HSC',
    shortName: 'MHS',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 63,
    facilities: 66,
    finances: 58,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 66,
    youthDevelopment: 70,
    logo: '🟠',
    primaryColor: '#FF6900',
    secondaryColor: '#003DA5',
  },
  {
    id: 'nantes',
    name: 'FC Nantes',
    shortName: 'FCN',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 63,
    facilities: 66,
    finances: 58,
    tacticalStyle: 'counter-attack',
    formation: '4-2-3-1',
    squadQuality: 66,
    youthDevelopment: 74,
    logo: '🟡',
    primaryColor: '#FDD835',
    secondaryColor: '#006633',
  },
  {
    id: 'reims',
    name: 'Stade de Reims',
    shortName: 'SDR',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 61,
    facilities: 64,
    finances: 56,
    tacticalStyle: 'possession',
    formation: '4-2-3-1',
    squadQuality: 66,
    youthDevelopment: 70,
    logo: '🔴',
    primaryColor: '#E2001A',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'brest',
    name: 'Stade Brestois',
    shortName: 'SB2',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 60,
    facilities: 62,
    finances: 54,
    tacticalStyle: 'counter-attack',
    formation: '4-3-3',
    squadQuality: 66,
    youthDevelopment: 64,
    logo: '🔴',
    primaryColor: '#E2001A',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'lorient',
    name: 'FC Lorient',
    shortName: 'FCL',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 59,
    facilities: 62,
    finances: 54,
    tacticalStyle: 'attacking',
    formation: '4-2-3-1',
    squadQuality: 64,
    youthDevelopment: 68,
    logo: '🟠',
    primaryColor: '#F47920',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'clermont',
    name: 'Clermont Foot',
    shortName: 'CF6',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 56,
    facilities: 58,
    finances: 50,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 60,
    youthDevelopment: 58,
    logo: '🔴',
    primaryColor: '#8B2346',
    secondaryColor: '#FDD835',
  },
  {
    id: 'le_havre',
    name: 'FC Le Havre',
    shortName: 'LHV',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 55,
    facilities: 60,
    finances: 50,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 60,
    youthDevelopment: 72,
    logo: '🔵',
    primaryColor: '#0055A4',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'metz',
    name: 'FC Metz',
    shortName: 'MET',
    league: 'ligue_1',
    country: 'France',
    tier: 1,
    reputation: 56,
    facilities: 58,
    finances: 50,
    tacticalStyle: 'defensive',
    formation: '4-4-2',
    squadQuality: 60,
    youthDevelopment: 64,
    logo: '🟤',
    primaryColor: '#7A003C',
    secondaryColor: '#FFFFFF',
  },
];

// Enrich raw club data with computed fields matching Club interface
function enrichClub(raw: Omit<Club, 'quality' | 'budget' | 'wageBudget' | 'squadSize' | 'style' | 'needsPositions'> & { squadQuality: number; finances: number; tacticalStyle: string }): Club {
  const styleMap: Record<string, { attacking: number; possession: number; pressing: number; defensive: number }> = {
    'attacking':     { attacking: 80, possession: 55, pressing: 65, defensive: 30 },
    'defensive':     { attacking: 30, possession: 45, pressing: 55, defensive: 80 },
    'counter-attack':{ attacking: 55, possession: 40, pressing: 60, defensive: 65 },
    'possession':    { attacking: 65, possession: 85, pressing: 50, defensive: 40 },
  };
  const allPositions: Position[] = ['GK','CB','LB','RB','CDM','CM','CAM','LW','RW','ST'];
  return {
    ...raw,
    quality: raw.squadQuality,
    budget: Math.round(raw.finances * raw.reputation * 5000),
    wageBudget: Math.round(raw.finances * raw.reputation * 100),
    squadSize: 22 + Math.floor(Math.random() * 6),
    style: styleMap[raw.tacticalStyle] ?? styleMap['possession'],
    needsPositions: allPositions.filter(() => Math.random() < 0.3).slice(0, 3),
  };
}

// Enriched clubs list matching the full Club type
export const ENRICHED_CLUBS: Club[] = (CLUBS as any[]).map(enrichClub);

// Helper: Get clubs by league
export function getClubsByLeague(leagueId: string): Club[] {
  return ENRICHED_CLUBS.filter(club => club.league === leagueId);
}

// Helper: Get club by ID
export function getClubById(id: string): Club | undefined {
  return ENRICHED_CLUBS.find(club => club.id === id);
}

// Helper: Get clubs by tier
export function getClubsByTier(tier: number): Club[] {
  return ENRICHED_CLUBS.filter(club => club.tier === tier);
}

// Helper: Get league info by ID
export function getLeagueById(leagueId: string) {
  return LEAGUES.find(league => league.id === leagueId);
}

// Helper: Get season length (total matchdays) for a league
export function getSeasonMatchdays(leagueId: string): number {
  const league = LEAGUES.find(l => l.id === leagueId);
  if (!league) return 38;
  return (league.teamCount - 1) * 2;
}
